wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/train.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
max_depth:
  desc: null
  value: null
n_estimators:
  desc: null
  value: 100
